FROM node:slim

RUN groupadd -r app && useradd -r -g app app

RUN mkdir -p /app && mkdir -p /home/app && chown -R app:app /app && chown -R app:app /home/app

# For PhantomJS installation
RUN apt-get update && apt-get install -y bzip2 git libfreetype6 libfreetype6-dev libfontconfig libfontconfig-dev

USER app

COPY src /app/src
COPY test /app/test
COPY bower.json /app/
COPY build.dist.js /app/
COPY karma.conf.js /app/
COPY package.json /app/
COPY protractor.conf.js /app/
COPY spec-bundle.js /app/
COPY tsconfig.json /app/
COPY tsd.json /app/
COPY typedoc.json /app/
COPY webpack.config.js /app/


WORKDIR /app
RUN cd /app
RUN ls

RUN ls && npm install
RUN node_modules/tsd/build/cli.js install
RUN node_modules/bower/bin/bower install

EXPOSE 3000

CMD ["npm", "start"]
