load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "services",
    srcs = ["calculator.go"],
    importpath = "github.com/vjftw/homomorphic-encryption/backend/services",
    visibility = ["//visibility:public"],
)

go_test(
    name = "services_test",
    srcs = ["calculator_test.go"],
    embed = [":services"],
    deps = ["@com_github_smartystreets_goconvey//convey:go_default_library"],
)
