sudo: required

language: ruby

services:
  - docker

before_install:
 - gem install rake

script:
 - ruby --version
 - cd backend && rake test
 - cd ..
 - cd api && rake test
 - cd ..
 - cd client && rake test
 - cd ..
 
