sudo: required
language: ruby
services:
- docker
before_install:
- gem install rake
env:
  global:
    # Composer GitHub token
    - secure: ZjYzQytdpGIbiMbZVP12H2iy6EZ9WXm5KYtMu+6itMXYewmCI1AgfVvtP0DWa6fU+m0jAHjgt/jdTX3ckk9gUIKRRQj587xsdguR+61Y34TJiM7Ob+lxYWljv8h6raYkOao4gjgzWimtIAhElXaBieyWpO8aiMTWiX+jrwtS38zeBI9mOd12urmhoZ6MFWWWI00RDWjpVtb2mnQoMNQ4LFKb1Ay5fN74k0tytAIUPosbTtgjfPtrEVh0ibrLjLUyNc8kjMvgDHQP0EXzjwiYShyIG21OusPLFanjvbIYhuTvi2o2VBj0vd9OmgFYHm2lQO2tMZnA+qUt9q/CzVZZV+qpFO8ay7QkulT+I9La5rBzxsfJomW5GOCUXmSP1jOngLBQ0Ia0Gb7AFq+aaXaUm1bhUrDC66lAwWC9tuBOY5ie9RviE8KkMicH/YpodM9sbKJMko9KE00FvQbPhkt3nFvApO/d1k3vPqovpuTGbSP7UiLi9hp6t9qy8Uo3AtcW5Xy92q+n+3ME27T8/Ds9n/1R/2JMGVkmhun/jnrSC5gzN6t1W3B5vEg7SN64Q/9l7VybYxNCvtCb5EYJsYi7miJ+42E0jb3yFxttUZkae0BmgyAgYmoi0Gl2GJQ4JKkMlZxdISo6Y6pBtLmxv1OJyFBqe+AxBCJ4eEKY+d2Ux3w=
    # Tutum Credentials
    - secure: j3GXiPzQD9SoREeDgBPG2Uvx6r3aY1FgAxcqQwN5xQeuoYCw24Rl3OtYzIxzSJC1ImWPbZjbSdwjz86iK1vmK0mpZjStvLW3pG6PHwrS01yKXTYZ2xX5xIpKC7TCwMP7mLNGeacBaTzjzWVO8NoiBkpjIL9NstRuGwB2oury5B7JTPPHsoAZWK5GTl/xPElGTW8+QuJcVJqy/pg//xqeD3p7dRajoSZDNjtwJ69FKB+oT5MS0imAkSM2DQtBxynYP7zIeY+AS6N97F77OiFv1pgpEcdHIlHR1cn/B+y+dap0vOIld0jxVaFzVVh4vfvnURuUB+VqzTZu9HepJYV/NMYl7w9b6HNbsXhrvtZ4FsPoAnnCzD6iyDEe12k5w+Ep4Ki4h86mSTcK7kjhOKNlPCtd3tWbrGc6ITRogA1FjqprCDLJRtZ21y7Soxyg/cfGdK1xH/LRbpbkwSw5IvmwnJrOb6lObRUpqeM+55DkZHT6DiYJblesSnDFKQA3h4lasyrmN0ZPpn//KUaarSWXK3LnAGvGYWPxa3VNz5P7PONArxt6ossK07cohCpdEhjfwqOLMlh5yEn2Gz/SE3R2fWatQt0xNdQS/T3oI3+/HluvGLjE381sjp0gkm11Ez2fpaaAgs+iOq+r1N+oaZCCOLUdjU8BKquaLrW4uT0EoN8=
    - secure: lFvv13B+Nb0sXP1QWCT+bWyKMilD0zLQGfECs6vLVybq25vti+fnpq1tmgX9qdH7FwHq9RqQnUEZemsJJ4yQzXgvTylFUQuUD8YpTy7io/o/wI+WSu7rSW3zhkLtlpnWEPLhtTv6Ihl/DCs4GduXBDyukOrFbF/04YovWzebPpTZKabRxFb3UVeHiA1Z8rPSgZb2Vj7fL0NUGipYpb7rQOMZLJDXsa14gawx4BPwyLRTpZg2BWRXo1/5lyT8Nzmvb3K0TjonMX72IZw815dqsqmT5t3WpnYaU+t/m/noqONiaocdLITxvtWj830avZG9aD4SP5LlibLgKZ4vFI+CJaivQBfvUygvThSdu4IyTPYcPZ6SH7eCss1BjcXTZ7d1L3HP2apwaBZmesjnt44sysQxvIBpAYCJ9eyXs0xghhjRlAX9igekbxzfWFMSfA4kKarczXs40kD3Xy44jYcD4nxwqNNos1Q3milRnxbKhMB2JWIab0m7/LhFeg720B9Lh95Ufnuz8+x/+bgt7S18MW4SnQ1uGr2MERYJycxSJUUwvjgqU0cG2ap3A+8+Si8Hcv48oKr2Vp1x5WYuRLxZNmAd4AE9XoCJDiwKhGjgqGaBPd2EShGQu+WGOMMNFdNVv6/4p/hxbfKZij2HUUk86WGpKr2ASkW4uJWFRlv2a9w=
    - secure: H4kktZCa/OWfzdl/917AQbjfOyhYoStAV+Tfzv/RxPx/+GkNrCUBgiouhV6qK5pN7G4uJXui9pARCRHQ6PSsYWAcP9RmZL40OA7ubPdak1gO9Y+l8VGpoSYEfZtQitrqKWMdnRyk+4dvOpsnDI9x9cGRT80U82iIEr7EfozM4OfPL0J9bycYAtvMQUF3RQYufGPhNdJN+FYnpmpb8zTUUQs4K4so12RRfgSprc1+Ndnkc3qxZqq0znPsaP9k9ImAkVeGNtR21QNQtdORWtn6KK5xV0rhI09hBnj+rjhvOtQPCECHjluM+1iOEltZuYWyCzX38/xKWnu49frgg67wU3hbjtwNs/TFVdWkrGqmfj+Q+JgG5TVXokwHQLNbV2LA+9+o2Q/2fc8Ct5uFymqt3ugVLxupiO/fitfJanubbhHketZw72+qRN1x+SaoRuxg4/rJJJCyzwEuKcwnTSXKP8HC/gSO7COZgfnZAEsKlJW4uQf0dlw41RTWZ3KljBrafx8JOx38aYnEUoWUKbZ5H8AHNm/65bmpVFAFbawpCS7iTjMM9APS8jFZb4qwZ2W7kgw12p1Nb3qRg5rMWtlRa3SlqRMKXH5oqO3ZjahbzhMhYHOCkw6GoEurKbMZkaB13rNCrFDIySxT5Zs4M7kYEEHha1M+Tosvyu4ikxt/6r0= 
  matrix:
  - TEST_SUITE=backend
  - TEST_SUITE=api
  - TEST_SUITE=client
script:
- ruby --version
- docker --version
- cd $TEST_SUITE && rake ci
- cd ..
cache:
  directories:
    - api/symfony/vendor
    - api/symfony/bin
    - client/node_modules
    - client/bower_components
    - client/typings
branches:
  only:
    - master
    - develop
