sudo: required
language: ruby
services:
- docker
before_install:
- gem install rake
env:
  - secure: ZjYzQytdpGIbiMbZVP12H2iy6EZ9WXm5KYtMu+6itMXYewmCI1AgfVvtP0DWa6fU+m0jAHjgt/jdTX3ckk9gUIKRRQj587xsdguR+61Y34TJiM7Ob+lxYWljv8h6raYkOao4gjgzWimtIAhElXaBieyWpO8aiMTWiX+jrwtS38zeBI9mOd12urmhoZ6MFWWWI00RDWjpVtb2mnQoMNQ4LFKb1Ay5fN74k0tytAIUPosbTtgjfPtrEVh0ibrLjLUyNc8kjMvgDHQP0EXzjwiYShyIG21OusPLFanjvbIYhuTvi2o2VBj0vd9OmgFYHm2lQO2tMZnA+qUt9q/CzVZZV+qpFO8ay7QkulT+I9La5rBzxsfJomW5GOCUXmSP1jOngLBQ0Ia0Gb7AFq+aaXaUm1bhUrDC66lAwWC9tuBOY5ie9RviE8KkMicH/YpodM9sbKJMko9KE00FvQbPhkt3nFvApO/d1k3vPqovpuTGbSP7UiLi9hp6t9qy8Uo3AtcW5Xy92q+n+3ME27T8/Ds9n/1R/2JMGVkmhun/jnrSC5gzN6t1W3B5vEg7SN64Q/9l7VybYxNCvtCb5EYJsYi7miJ+42E0jb3yFxttUZkae0BmgyAgYmoi0Gl2GJQ4JKkMlZxdISo6Y6pBtLmxv1OJyFBqe+AxBCJ4eEKY+d2Ux3w=
  - TEST_SUITE=backend
  - TEST_SUITE=api
  - TEST_SUITE=client
script:
- ruby --version
- cd $TEST_SUITE && rake test && rake publish_coverage
- cd ..
cache:
  directories:
    - api/symfony/vendor
    - api/symfony/bin
    - client/node_modules
    - client/bower_components
    - client/typings
