version: '2'

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: /bin/bash -c "npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: /bin/bash -c "php -v && composer install && chmod +x setup.sh && ./setup.sh && bin/console server:run 0.0.0.0:8000"
    environment:
      SYMFONY__DATABASE_HOST: database
      SYMFONY__DATABASE_NAME: homomorphic_encryption
      SYMFONY__DATABASE_PASSWORD: homo_enc_123
      SYMFONY__DATABASE_PORT: 3306
      SYMFONY__DATABASE_USER: root
      SYMFONY__JMS_SERIALIZER__CAMEL_CASE_NAMING_STRATEGY__CLASS: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
      SYMFONY__MAILER_HOST: 127.0.0.1
      SYMFONY__MAILER_PASSWORD: temp
      SYMFONY__MAILER_TRANSPORT: smtp
      SYMFONY__MAILER_USER: temp
      SYMFONY__REDIS_HOST: redis://cache
      SYMFONY__SECRET: a0d5172eb810f55c5bdb22be331fea6f6841ea2f
      SYMFONY__ENV: dev
    links:
      - "mysql:database"
      - "redis:cache"
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    volumes:
      - "./api/symfony:/app"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: /bin/bash -c "python3 start_backend.py"
    environment:
      REDIS_HOST: cache
      WS_PORT: 9000
    links:
      - "redis:cache"
    ports:
      - "9000:9000"
    volumes:
      - "./backend:/app"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: homo_enc_123
    expose:
      - "3306"

  redis:
    image: redis:latest
    expose:
      - "6379"
