# Tell Gazelle to stop replacing rules-proto-grpc rules.
# (https://github.com/rules-proto-grpc/rules_proto_grpc/issues/220)
# gazelle:ignore
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_proto_grpc_grpc_gateway//:defs.bzl", "gateway_grpc_library", "gateway_openapiv2_combined_compile")
load("//macros:write_go_generated_src_files.bzl", "write_go_generated_source_files")

proto_library(
    name = "v1",
    srcs = [
        "compute_service.proto",
        "v1.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@@grpc_ecosystem_grpc_gateway+//protoc-gen-openapiv2/options:options_proto",
        "@googleapis//google/api:annotations_proto",
        "@protobuf//:any_proto",
    ],
)

gateway_openapiv2_combined_compile(
    name = "openapiv2_json",
    protos = [":v1"],
    visibility = ["//visibility:public"],
)

gateway_grpc_library(
    name = "go",
    importpath = "github.com/vjftw/homomorphic-encryption/api/v1",
    protos = [":v1"],
    visibility = ["//visibility:public"],
    deps = [
        "@@grpc_ecosystem_grpc_gateway+//protoc-gen-openapiv2/options",
        "@org_golang_google_genproto_googleapis_api//annotations",
    ],
)

write_go_generated_source_files(
    name = "gen_srcs",
    output_files = [
        "v1.pb.go",
        "compute_service.pb.gw.go",
        "compute_service_grpc.pb.go",
        "compute_service.pb.go",
    ],
    target = ":go_pb",
)
