syntax = "proto3";

package api.homomorphic_encryption.v1;

import "google/api/annotations.proto";

option go_package = "github.com/vjftw/homomorphic-encryption/api/homomorphic_encryption/v1";

service ComputeService {
  rpc Compute(ComputeRequest) returns (ComputeResponse) {
    option (google.api.http) = {
      post: "/compute"
      body: "*"
    };
  }
}

message ComputeRequest {
  map<string, string> public_scope = 1;
  repeated string steps = 2;
}

message ComputeResponse {
  ComputeRequest compute_request = 1;

  map<string, string> public_scope = 2;
}
