// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/v1/v1.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_v1_v1_proto protoreflect.FileDescriptor

const file_api_v1_v1_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/v1/v1.proto\x12\x1dapi.homomorphic_encryption.v1\x1a.protoc-gen-openapiv2/options/annotations.protoB\xc6\x02\x92A\xfb\x01\x12\xcb\x01\n" +
	"\x16Homomorphic Encryption\"Z\n" +
	"'github.com/VJftw/homomorphic-encryption\x12/https://github.com/VJftw/homomorphic-encryption*P\n" +
	"\vMIT License\x12Ahttps://github.com/VJftw/homomorphic-encryption/blob/main/LICENSE2\x031.0\"\a/api/v12\x10application/json:\x10application/jsonZEgithub.com/vjftw/homomorphic-encryption/api/homomorphic_encryption/v1b\x06proto3"

var file_api_v1_v1_proto_goTypes = []any{}
var file_api_v1_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_v1_proto_init() }
func file_api_v1_v1_proto_init() {
	if File_api_v1_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_v1_proto_rawDesc), len(file_api_v1_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_v1_proto_goTypes,
		DependencyIndexes: file_api_v1_v1_proto_depIdxs,
	}.Build()
	File_api_v1_v1_proto = out.File
	file_api_v1_v1_proto_goTypes = nil
	file_api_v1_v1_proto_depIdxs = nil
}
