FROM alpine:3.2

# Install Python3, pip and openssl
RUN apk add --update python3 python3-dev openssl && rm -rf /var/cache/apk
RUN wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && rm get-pip.py

RUN mkdir -p /app
WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt
RUN pip install -r tests/requirements.txt
