FROM vjftw/ubuntu

# Install pip
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py

# Install app deps
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt

# Install dev deps
COPY tests/requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt

RUN rm /tmp/requirements.txt

VOLUME /app
EXPOSE 9000
