FROM sillelien/base-alpine:0.10

# Install Python3, pip and openssl
RUN apk add --update python3 python3-dev wget openssl && rm -rf /var/apk/cache

RUN wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && rm get-pip.py

RUN mkdir -p /app
WORKDIR /app

COPY . /app

RUN rm -rf .idea venv tests

RUN pip install -r requirements.txt

EXPOSE 9000

COPY start_backend.sh /etc/services.d/fhe_backend/run
RUN chmod 755 /etc/services.d/fhe_backend/run
