FROM vjftw/ubuntu

# Install pip
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py

# Install app deps
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt

RUN rm /tmp/requirements.txt

COPY start_backend.sh /etc/services.d/fhe_backend/run
RUN chmod 755 /etc/services.d/fhe_backend/run

COPY . /app
RUN rm -rf .idea venv tests

VOLUME /app
EXPOSE 9000
