load("@bazel_skylib//rules:copy_directory.bzl", "copy_directory")
load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "frontend",
    srcs = [
        "baseof.go",
        "frontend.go",
        "index.go",
        "routes.go",
        "schemes.go",
        "schemes-list.go",
        "schemes-single.go",
    ],
    embedsrcs = [":schemes"],
    importpath = "github.com/vjftw/homomorphic-encryption/pkg/frontend",
    visibility = ["//pkg/frontend:__subpackages__"],
    deps = [
        "//api/v1:go",
        "//pkg/compute",
        "@com_github_maxence_charriere_go_app_v10//pkg/app",
        "@in_gopkg_yaml_v3//:yaml_v3",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)

copy_directory(
    name = "schemes",
    src = "//schemes",
    out = "schemes",
)
