FROM alpine:latest

ADD https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.38.zip /tmp/go_appengine.zip
RUN unzip /tmp/go_appengine.zip -d /

ADD https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-117.0.0-linux-x86_64.tar.gz /tmp/google-cloud-sdk.tar.gz
RUN tar -xzf /tmp/google-cloud-sdk.tar.gz -C /

ENV PATH $PATH:/go_appengine/:/google-cloud-sdk/bin

RUN apk add --update python

VOLUME /app
