load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "compute",
    srcs = [
        "calculator.go",
        "v1.go",
    ],
    importpath = "github.com/vjftw/homomorphic-encryption/pkg/compute",
    visibility = [
        "//cmd:__subpackages__",
        "//pkg/frontend:__subpackages__",
    ],
    deps = [
        "//api/v1:go",
    ],
)

go_test(
    name = "compute_test",
    size = "small",
    srcs = ["calculator_test.go"],
    deps = [
        ":compute",
        "@com_github_stretchr_testify//assert",
    ],
)
