load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_binary(
    name = "cmd",
    embed = [":cmd_lib"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "cmd_lib",
    srcs = ["main.go"],
    importpath = "github.com/vjftw/homomorphic-encryption/cmd",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/compute",
        "//pkg/docs",
        "//pkg/frontend/static",
        "@//api/v1:go",
        "@@grpc_ecosystem_grpc_gateway+//runtime",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_x_sync//errgroup",
    ],
)
