load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "models",
    srcs = ["computation-model.go"],
    importpath = "github.com/vjftw/homomorphic-encryption/backend/models",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_appengine//datastore:go_default_library",
        "@org_golang_x_net//context",
    ],
)
