// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: api/homomorphic_encryption/v1/homomorphic_encryption.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComputeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicScope   map[string]string      `protobuf:"bytes,1,rep,name=public_scope,json=publicScope,proto3" json:"public_scope,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Steps         []string               `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeRequest) Reset() {
	*x = ComputeRequest{}
	mi := &file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeRequest) ProtoMessage() {}

func (x *ComputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeRequest.ProtoReflect.Descriptor instead.
func (*ComputeRequest) Descriptor() ([]byte, []int) {
	return file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeRequest) GetPublicScope() map[string]string {
	if x != nil {
		return x.PublicScope
	}
	return nil
}

func (x *ComputeRequest) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

type ComputeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ComputeRequest *ComputeRequest        `protobuf:"bytes,1,opt,name=compute_request,json=computeRequest,proto3" json:"compute_request,omitempty"`
	PublicScope    map[string]string      `protobuf:"bytes,2,rep,name=public_scope,json=publicScope,proto3" json:"public_scope,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComputeResponse) Reset() {
	*x = ComputeResponse{}
	mi := &file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeResponse) ProtoMessage() {}

func (x *ComputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeResponse.ProtoReflect.Descriptor instead.
func (*ComputeResponse) Descriptor() ([]byte, []int) {
	return file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_rawDescGZIP(), []int{1}
}

func (x *ComputeResponse) GetComputeRequest() *ComputeRequest {
	if x != nil {
		return x.ComputeRequest
	}
	return nil
}

func (x *ComputeResponse) GetPublicScope() map[string]string {
	if x != nil {
		return x.PublicScope
	}
	return nil
}

var File_api_homomorphic_encryption_v1_homomorphic_encryption_proto protoreflect.FileDescriptor

const file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_rawDesc = "" +
	"\n" +
	":api/homomorphic_encryption/v1/homomorphic_encryption.proto\x12\x1dapi.homomorphic_encryption.v1\x1a\x19google/protobuf/any.proto\"\xc9\x01\n" +
	"\x0eComputeRequest\x12a\n" +
	"\fpublic_scope\x18\x01 \x03(\v2>.api.homomorphic_encryption.v1.ComputeRequest.PublicScopeEntryR\vpublicScope\x12\x14\n" +
	"\x05steps\x18\x02 \x03(\tR\x05steps\x1a>\n" +
	"\x10PublicScopeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x02\n" +
	"\x0fComputeResponse\x12V\n" +
	"\x0fcompute_request\x18\x01 \x01(\v2-.api.homomorphic_encryption.v1.ComputeRequestR\x0ecomputeRequest\x12b\n" +
	"\fpublic_scope\x18\x02 \x03(\v2?.api.homomorphic_encryption.v1.ComputeResponse.PublicScopeEntryR\vpublicScope\x1a>\n" +
	"\x10PublicScopeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012z\n" +
	"\x0eComputeService\x12h\n" +
	"\aCompute\x12-.api.homomorphic_encryption.v1.ComputeRequest\x1a..api.homomorphic_encryption.v1.ComputeResponseBGZEgithub.com/vjftw/homomorphic-encryption/api/homomorphic-encryption/v1b\x06proto3"

var (
	file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_rawDescOnce sync.Once
	file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_rawDescData []byte
)

func file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_rawDescGZIP() []byte {
	file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_rawDescOnce.Do(func() {
		file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_rawDesc), len(file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_rawDesc)))
	})
	return file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_rawDescData
}

var file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_goTypes = []any{
	(*ComputeRequest)(nil),  // 0: api.homomorphic_encryption.v1.ComputeRequest
	(*ComputeResponse)(nil), // 1: api.homomorphic_encryption.v1.ComputeResponse
	nil,                     // 2: api.homomorphic_encryption.v1.ComputeRequest.PublicScopeEntry
	nil,                     // 3: api.homomorphic_encryption.v1.ComputeResponse.PublicScopeEntry
}
var file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_depIdxs = []int32{
	2, // 0: api.homomorphic_encryption.v1.ComputeRequest.public_scope:type_name -> api.homomorphic_encryption.v1.ComputeRequest.PublicScopeEntry
	0, // 1: api.homomorphic_encryption.v1.ComputeResponse.compute_request:type_name -> api.homomorphic_encryption.v1.ComputeRequest
	3, // 2: api.homomorphic_encryption.v1.ComputeResponse.public_scope:type_name -> api.homomorphic_encryption.v1.ComputeResponse.PublicScopeEntry
	0, // 3: api.homomorphic_encryption.v1.ComputeService.Compute:input_type -> api.homomorphic_encryption.v1.ComputeRequest
	1, // 4: api.homomorphic_encryption.v1.ComputeService.Compute:output_type -> api.homomorphic_encryption.v1.ComputeResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_init() }
func file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_init() {
	if File_api_homomorphic_encryption_v1_homomorphic_encryption_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_rawDesc), len(file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_goTypes,
		DependencyIndexes: file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_depIdxs,
		MessageInfos:      file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_msgTypes,
	}.Build()
	File_api_homomorphic_encryption_v1_homomorphic_encryption_proto = out.File
	file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_goTypes = nil
	file_api_homomorphic_encryption_v1_homomorphic_encryption_proto_depIdxs = nil
}
